---
language: node_js
node_js:
  - "10"

sudo: required

cache:
  yarn: true

before_install:
  - set -e
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      AWS_BUCKET="search.ror.org";
      CLOUDFRONT_DISTRIBUTION_ID=$CLOUDFRONT_DISTRIBUTION_ID;
      cp .env.production .env;
      AUTO_DEPLOY=true;
    elif [ "$TRAVIS_BRANCH" == "dev" ]; then
      AWS_BUCKET="search.dev.ror.org";
      CLOUDFRONT_DISTRIBUTION_ID=$CLOUDFRONT_DISTRIBUTION_DEV_ID;
      cp .env.dev .env;
      AUTO_DEPLOY=true;
    else
      AWS_BUCKET="search.ror.org";
      CLOUDFRONT_DISTRIBUTION_ID=$CLOUDFRONT_DISTRIBUTION_ID;
      cp .env.production .env;
    fi
  - npm config set spin false
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --non-interactive
  - sudo pip install awscli
  - curl -sL https://sentry.io/get-cli/ | bash
  - sentry-cli --version

script:
  - yarn test
  - ember build --environment=production

after_success:
  # Send release information to Sentry
  - if [ "$AUTO_DEPLOY" == "true" ]; then
      GIT_TAG=$(git describe --tags $(git rev-list --tags --max-count=1));
      sentry-cli releases new ror-app:${GIT_TAG} --finalize --project ror-app;

      if [ "${TRAVIS_TAG?}" ]; then
        sentry-cli releases deploys ror-app:${GIT_TAG} new -e production;
      else
        sentry-cli releases deploys ror-app:${GIT_TAG} new -e dev;
      fi

      sentry-cli releases set-commits --auto ror-app:${GIT_TAG};
    fi

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_BUCKET
  region: eu-west-1
  skip_cleanup: true
  local_dir: dist
  acl: public_read
  cache_control: "no-cache"
  on:
    all_branches: true

after_deploy:
  - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
  - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

notifications:
  email: false
